language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
- PLONE_VERSION=4.2
- PLONE_VERSION=4.3
- PLONE_VERSION=5.0
matrix:
  fast_finish: true
before_install:
- pip install -r requirements.txt
install:
- sed -ie "s#test-4.3.x.cfg#test-$PLONE_VERSION.x.cfg#" buildout.cfg
- buildout annotate
- buildout
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage --output-dir=parts/test/coverage
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
