language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
  - downloads
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=51
    - python: "2.7"
      env: PLONE_VERSION=52
    - python: "3.6"
      env: PLONE_VERSION=52
    - python: "3.7"
      env: PLONE_VERSION=52
      dist: xenial
fast_finish: true
before_install:
  - pyversion=$(python --version 2>&1)
  - if [ ${pyversion:7:1} = 3 ]; then pip install black; else echo "Skip black install"; fi
  - pip install -r requirements.txt -c constraints_plone${PLONE_VERSION}.txt

install:
  - buildout -c test_plone${PLONE_VERSION}.cfg -N -t 3 code-analysis:return-status-codes=True annotate
  - buildout -c test_plone${PLONE_VERSION}.cfg -N -t 3 code-analysis:return-status-codes=True

script:
  - if [ ${pyversion:7:1} = 3 ]; then black --check; else echo "Skip black check"; fi
  - bin/test --all

after_script:
  - bin/createcoverage --output-dir=parts/test/coverage

after_success:
  - pip install coverage
  - python -m coverage.pickle2json
  - pip install -q coveralls
  - coveralls
