name: CI

on:
  push:
    branches-ignore:
      - "master"
      - "releases/**"
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        config:
        # [Python version, tox env]
        - ["3.6",   "plone52-py36"]
        - ["3.7",   "plone52-py37"]
        - ["3.8",   "plone52-py38"]
#        - ["3.9",   "plone52-py39"]
#        - ["3.7",   "plone60-py37"]
#        - ["3.8",   "plone60-py38"]
#        - ["3.9",   "plone60-py39"]
    runs-on: ubuntu-latest
    name: ${{ matrix.config[1] }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config[0] }}
    - name: Pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.config[0] }}-${{ hashFiles('setup.*', 'tox.ini') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.config[0] }}-
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox coverage
    - name: Test
      run: tox -e ${{ matrix.config[1] }}
    - name: Upload coverage data to coveralls.io
      run: coveralls --service=github
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.config[1] }}
          COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: build
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Coveralls Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}